http:
  server_port: 9123

# default_config:
# no default config, be more specific and select from https://www.home-assistant.io/integrations/default_config/
automation:
# cloud:
config:
counter:
dhcp:
frontend:
history:
image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
media_source:
mobile_app:
person:
scene:
script:
ssdp:
sun:
system_health:
tag:
timer:
updater:
zeroconf:
zone:

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

# enable remote python debugger
debugpy:

# debug logging for govee integration
logger:
  default: info
  logs:
    homeassistant.components.govee: debug
    custom_components.govee: debug
    govee_api_laggat: debug
    custom_components.hacs: warning
    homeassistant.components.discovery: debug
    homeassistant.components.zeroconf: debug
    homeassistant.components.ssdp: debug
    homeassistant.components.dhcp: debug


device_tracker:
  - platform: bluetooth_le_tracker
    # avoid some log spam
    interval_seconds: 60
    track_new_devices: true
